### ISSUE TITLE
week 9 ready for review

### ISSUE THREAD

**Issue by davidtcalabrese** [mad-ent-java-s22/week-9-exercise#1]
@pawaitemadisoncollege 

This was very hard for me. I couldn't get the pom.xml right, I was looking for examples online but they weren't working. Then I had a hard time returning the entities correctly.

**Comment by pawaitemadisoncollege** [comment]
Despite the struggles you identified, you achieved the goal with the week 9 exercise!

With this knowledge, you *could* write services to access all data, and then call those services from the front end, bypassing the servlets that we've typically used in our java web dev so far.  I suspect in industry, we'll start seeing more of this model (front end to service).
